[{
    "company_name":"hcl",
    "date":ISODate("2020-09-25"),
    "students_appeared":"sahana,dev,raja"
},
{
    "company_name":"cts",
    "date":ISODate("2020-10-16"),
    "students_appeared":"iniya,surya,sandhya"
},
{
    "company_name":"tcs",
    "date":ISODate("2020-10-27"),
    "students_appeared":"risaanth,nivetha"
},
{
    "company_name":"zoho",
    "date":ISODate("2020-07-15"),
    "students_appeared":"vinithra,naveen"
}
}]
